# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
react:
  title: yddtz's Blog
  name: yddtz
  menu_right_subtitle: Blogger || Computer Scientist
  avatar: http://api.adorable.io/avatar/aplaza@liquidthink.net
  logo: static/img/logo_theme.jpg
  email: zjmem@sohu.com
  description: > # this means to ignore newlines until "baseurl:"
    
  baseurl: "" # the subpath of your site, e.g. /blog
  url: "http://test_domain.com:4000" # the base hostname & protocol for your site
  permalink: /:year/:month/:day/:title
  social:
    twitter:
    github:
    facebook:
    code:
    google-plus:
    rss: feed.xml



title: yddtz's Blog
name: yddtz
menu_right_subtitle: Blogger || Computer Scientist
avatar: http://api.adorable.io/avatar/aplaza@liquidthink.net
logo: static/img/logo_theme.jpg
email: zjmem@sohu.com
description: > # this means to ignore newlines until "baseurl:"
    
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://test_domain.com:4000" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title

twitter_username:
github_username:


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

source: src
destination: public

assets:
  compress:
    css: sass
    js: false

  autowrite: true
  cache: .asset-cache
  cache_type: filesystem
  cdn: www.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true

  assets:
    - "*.png"
    - "bundle.css"
    - "bundle.js.map"
    - "*.svg"
    - "*.eof"
    - "*.ttf"

  sources:
    - src/_assets/css
    - src/_assets/fonts
    - src/_assets/img
    - src/_assets/projects

  features:
    liquid: false
    integrity: true
    automatic_img_size: true
    automatic_img_alt : true

exclude: ['node_modules', 'Gemfile', '.asset-cache', 'build-prod.sh', 'build-dev.sh']

gems:
  - jekyll-assets
  - jekyll_pages_api
  - jekyll-react
